//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace WinForms.Ribbon
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint Application = 26;
            public const uint RecentItems = 1003;
            public const uint Open = 1001;
            public const uint Save = 1002;
            public const uint Options = 2002;
            public const uint About = 2001;
            public const uint Exit = 2003;
            public const uint Help = 33;
            public const uint Qat = 25;
            public const uint Home = 2;
            public const uint Clipboard = 4;
            public const uint PasteSplit = 3012;
            public const uint Paste = 3002;
            public const uint PasteHex = 3005;
            public const uint Cut = 3001;
            public const uint Copy = 3003;
            public const uint CopyHex = 3004;
            public const uint Editing = 5;
            public const uint Find = 4001;
            public const uint FindNext = 4002;
            public const uint FindPrevious = 32;
            public const uint GoTo = 4003;
            public const uint SelectAll = 4004;
            public const uint Views = 23;
            public const uint Encoding = 22;
            public const uint Bits = 24;
            public const uint CutContext = 29;
            public const uint CopyContext = 30;
            public const uint PasteContext = 31;
            public const uint SelectAllContext = 28;
            public const uint ContextMenus = 27;
        }

        // ContextPopup CommandName
        public const uint ContextMenus = Cmd.ContextMenus;

        public RibbonStrip Ribbon { get; private set; }
        public RibbonApplicationMenu Application { get; private set; }
        public RibbonRecentItems RecentItems { get; private set; }
        public RibbonButton Open { get; private set; }
        public RibbonButton Save { get; private set; }
        public RibbonButton Options { get; private set; }
        public RibbonButton About { get; private set; }
        public RibbonButton Exit { get; private set; }
        public RibbonHelpButton Help { get; private set; }
        public RibbonQuickAccessToolbar Qat { get; private set; }
        public RibbonTab Home { get; private set; }
        public RibbonGroup Clipboard { get; private set; }
        public RibbonSplitButton PasteSplit { get; private set; }
        public RibbonButton Paste { get; private set; }
        public RibbonButton PasteHex { get; private set; }
        public RibbonButton Cut { get; private set; }
        public RibbonButton Copy { get; private set; }
        public RibbonButton CopyHex { get; private set; }
        public RibbonGroup Editing { get; private set; }
        public RibbonButton Find { get; private set; }
        public RibbonButton FindNext { get; private set; }
        public RibbonButton FindPrevious { get; private set; }
        public RibbonButton GoTo { get; private set; }
        public RibbonButton SelectAll { get; private set; }
        public RibbonGroup Views { get; private set; }
        public RibbonComboBox Encoding { get; private set; }
        public RibbonCheckBox Bits { get; private set; }
        public RibbonButton CutContext { get; private set; }
        public RibbonButton CopyContext { get; private set; }
        public RibbonButton PasteContext { get; private set; }
        public RibbonButton SelectAllContext { get; private set; }

        public RibbonItems(RibbonStrip ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            Application = new RibbonApplicationMenu(ribbon, Cmd.Application);
            RecentItems = new RibbonRecentItems(ribbon, Cmd.RecentItems);
            Open = new RibbonButton(ribbon, Cmd.Open);
            Save = new RibbonButton(ribbon, Cmd.Save);
            Options = new RibbonButton(ribbon, Cmd.Options);
            About = new RibbonButton(ribbon, Cmd.About);
            Exit = new RibbonButton(ribbon, Cmd.Exit);
            Help = new RibbonHelpButton(ribbon, Cmd.Help);
            Qat = new RibbonQuickAccessToolbar(ribbon, Cmd.Qat);
            Home = new RibbonTab(ribbon, Cmd.Home);
            Clipboard = new RibbonGroup(ribbon, Cmd.Clipboard);
            PasteSplit = new RibbonSplitButton(ribbon, Cmd.PasteSplit);
            Paste = new RibbonButton(ribbon, Cmd.Paste);
            PasteHex = new RibbonButton(ribbon, Cmd.PasteHex);
            Cut = new RibbonButton(ribbon, Cmd.Cut);
            Copy = new RibbonButton(ribbon, Cmd.Copy);
            CopyHex = new RibbonButton(ribbon, Cmd.CopyHex);
            Editing = new RibbonGroup(ribbon, Cmd.Editing);
            Find = new RibbonButton(ribbon, Cmd.Find);
            FindNext = new RibbonButton(ribbon, Cmd.FindNext);
            FindPrevious = new RibbonButton(ribbon, Cmd.FindPrevious);
            GoTo = new RibbonButton(ribbon, Cmd.GoTo);
            SelectAll = new RibbonButton(ribbon, Cmd.SelectAll);
            Views = new RibbonGroup(ribbon, Cmd.Views);
            Encoding = new RibbonComboBox(ribbon, Cmd.Encoding);
            Bits = new RibbonCheckBox(ribbon, Cmd.Bits);
            CutContext = new RibbonButton(ribbon, Cmd.CutContext);
            CopyContext = new RibbonButton(ribbon, Cmd.CopyContext);
            PasteContext = new RibbonButton(ribbon, Cmd.PasteContext);
            SelectAllContext = new RibbonButton(ribbon, Cmd.SelectAllContext);
        }

    }
}
